<?php
namespace app\common\logic;

use think\Db;
use think\Model;

class Users extends Model
{
    protected $dao;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->dao = \think\Loader::model('Users');
    }

    public function getOneById($id, $columns = ['*'])
    {
        return $this->dao
            ->where('id', $id)
            ->field($columns)
            ->find();
    }

    public function getAllListsByWhere($where, $columns = ['*'])
    {
        $userInfo = $this->dao
            ->where($where)
            ->field($columns)
            ->select();
//        foreach($userInfo as $k=>$v){
//            $a = \think\Loader::model('AuthGroupAccess')
//                ->alias('a')
//                ->join('diy_auth_group b', 'a.group_id = b.id', 'LEFT')
//                ->where('a.uid', $v['uid'])
//                ->find();
//            if($a){
//                $b = $a->toArray();
//                $userInfo[$k]['group_name'] = '';
//            }else{
//                $userInfo[$k]['group_name'] = '';
//            }
//        }
        return $userInfo;
    }

    public function getOneByWhere($where, $columns = ['*'])
    {
        return $this->dao
            ->where($where)
            ->field($columns)
            ->find();
    }
}